input: /data/Daan/Projects/Pool1_Pool2_Tiling/Input/mpox_example_fastq_all.csv
outdir: /data/Daan/Projects/Pool1_Pool2_Tiling/Output
fasta: /data/Daan/Projects/nextflow-metatropics-INRB/Databases/Human/chm13v2.0.fa
#host_fasta: /data/Daan/Projects/nextflow-metatropics-INRB/Databases/Aedes/Aedes_aegypti.fasta
dbmeta: /data/Daan/Projects/nextflow-metatropics-INRB/Databases/ViralRefseq
minLength: 200
pair: true
front: 25
tail: 25
minVirus: 0.01
quality: 20 # You can adapt this to '30' to reach Illumina quality
depth: 30 # When wanting high-quality genomes better adapt this to '20"
agreement: 0.8
rcoverage_figure: true

# Rarefaction parameters
perform_rarefaction: true # Preferably rarefy to a reasonable number of input to decrease time of analysis
target_bases: 500000000

# Cleanup module
enable_docker_cleanup: false
